### ISSUE TITLE
Add `Validation` to `ProviderSpec`

### ISSUE THREAD

**Issue by afritzler** [onmetal/machine-controller-manager-provider-onmetal#47]
# Summary

In order to ensure the correct behaviour of the MCM driver, the `ProviderSpec` validation needs to be implemented. Here the corresponding implementation (https://github.com/onmetal/machine-controller-manager-provider-onmetal/blob/main/api/validation/validation.go) needs to be improved.

## Definition of done

Ensure the correct `ProviderSpec` and ensure the behaviour by providing corresponding unit tests.

**Comment by Ashughorla** [comment]
New PR is raised.
[PR-68](https://github.com/onmetal/machine-controller-manager-provider-onmetal/pull/68)
